/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#1b1c1e",
        "primary": "#000000",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f7",
        "on-tertiary-fixed-variant": "#43474e",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed": "#dfe2eb",
        "surface-dim": "#dadad8",
        "on-surface": "#1a1c1b",
        "secondary": "#3c674c",
        "surface-container-low": "#f4f4f2",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#181c22",
        "on-secondary-container": "#406c50",
        "secondary-fixed-dim": "#a2d2b0",
        "outline": "#76777b",
        "surface-tint": "#5e5e60",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#baebc8",
        "on-primary-container": "#848386",
        "background": "#f9f9f7",
        "tertiary-fixed-dim": "#c3c6cf",
        "inverse-on-surface": "#f1f1ef",
        "inverse-surface": "#2f3130",
        "on-background": "#1a1c1b",
        "tertiary-container": "#181c22",
        "on-primary-fixed-variant": "#464749",
        "tertiary": "#000000",
        "primary-fixed": "#e3e2e4",
        "surface-container-highest": "#e2e3e1",
        "surface-variant": "#e2e3e1",
        "on-secondary-fixed": "#002110",
        "on-surface-variant": "#45474a",
        "primary-fixed-dim": "#c7c6c8",
        "outline-variant": "#c6c6ca",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1b1c1e",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#bdeecb",
        "surface": "#f9f9f7",
        "inverse-primary": "#c7c6c8",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#234f35",
        "surface-container": "#eeeeec",
        "on-tertiary-container": "#80848b",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "margin": "3rem"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "23px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "title-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "19px", "fontWeight": "400" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["17px", { "lineHeight": "26px", "fontWeight": "400" }],
        "display-lg-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
